### ISSUE TITLE
Raises http.client.BadStatusLine in Ubuntu 14.04 x64 on switch_to_repositories (cntlm proxy)

### ISSUE THREAD

**Issue by jiri-janousek** [tiliado/tiliado-repositories#1]
Raises http.client.BadStatusLine in Ubuntu 14.04 x64 on switch_to_repositories

```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/tiliadoweb/installer.py", line 85, in on_sign_in_clicked
self.switch_to_repositories()
File "/usr/lib/python3/dist-packages/tiliadoweb/installer.py", line 139, in switch_to_repositories
self.repositories_page.set_repositories([repo for repo in self.api.repositories if repo["active"]])
File "/usr/lib/python3/dist-packages/tiliadoweb/api.py", line 77, in repositories
return self.make_request("repository/repositories/")
File "/usr/lib/python3/dist-packages/tiliadoweb/api.py", line 64, in make_request
response = urlopen(request)
File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib/python3.4/urllib/request.py", line 463, in open
response = self._open(req, data)
File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
'_open', req)
File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
result = func(*args)
File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
context=self._context, check_hostname=self._check_hostname)
File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
h.request(req.get_method(), req.selector, req.data, headers)
File "/usr/lib/python3.4/http/client.py", line 1088, in request
self._send_request(method, url, body, headers)
File "/usr/lib/python3.4/http/client.py", line 1126, in _send_request
self.endheaders(body)
File "/usr/lib/python3.4/http/client.py", line 1084, in endheaders
self._send_output(message_body)
File "/usr/lib/python3.4/http/client.py", line 922, in _send_output
self.send(msg)
File "/usr/lib/python3.4/http/client.py", line 857, in send
self.connect()
File "/usr/lib/python3.4/http/client.py", line 1223, in connect
super().connect()
File "/usr/lib/python3.4/http/client.py", line 837, in connect
self._tunnel()
File "/usr/lib/python3.4/http/client.py", line 815, in _tunnel
(version, code, message) = response._read_status()
File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

**Comment by jiri-janousek** [comment]
Hello @MaikoID, did this error happen only once or multiple times?

**Comment by MaikoID** [comment]
Hi @fenryxo it happened multiple times. I'm behind a proxy handled by cntlm. This environment may be the cause but I think it's odd once I've installed it in the past.

**Comment by jiri-janousek** [comment]
> I'm behind a proxy handled by cntlm. 

That might be the cause of the issue. Proxy support is always tricky, especially on older systems like Ubuntu 14.04. 

> This environment may be the cause but I think it's odd once I've installed it in the past.

Maybe a system package have been updated since then. Anyway. I hope to look at it today evening.

**Comment by jiri-janousek** [comment]
Hello. I've just tried Tiliado Repositories Installer in Ubuntu 14.04 behind HTTP proxy without authentication and it works. Maybe cntlm is the problem.

**Comment by MaikoID** [comment]
You can close the issue then, I think it's too environment specific and I'm directly using the ppa without issues.

**Comment by jiri-janousek** [comment]
OK then :-)
